karo/urls.py
from django.urls import path, include
from .views import KaroList, KaroDetail, KaroCreate, KaroDelete, KaroUpdate, fulldelete



urlpatterns = [
    path("list/", KaroList, name="list"),
    path("detail/<int:pk>", KaroDetail.as_view(), name="detail"),
    path("create/", KaroCreate.as_view(), name="create"),
    path("delete/<int:pk>", KaroDelete.as_view(), name="delete"),
    path("update/<int:pk>", KaroUpdate.as_view(), name="update"),

    path("fulldelete/", fulldelete, name="fulldelete"),
    
]

karopro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("karo.urls")),
]

karo/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

CHOICE = (("secondary", "NIGHT"), ("primary", "DAYTIME"), ("danger", "MORNING"))

class KaroModel(models.Model):
    #食べたもの
    eat = models.CharField(max_length=20)
    #食べたもののカロリー
    kcol = models.IntegerField(null=True, blank=True, default=0)
    #食べた時間帯（朝、昼、夜）
    daycolor = models.CharField(
        max_length=10,
        choices = CHOICE,
        default = "secondary"
        )
    #食べた時間
    date = models.DateTimeField(default=timezone.now())
    #目標カロリーの設定
    goleKcol = models.IntegerField(default=0)

    def __str__(self):
        return self.eat

karo/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from .models import KaroModel
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.db.models import Count, Avg, Sum, Max, Min

import datetime

# Create your views here.

def KaroList(request):
    object_list=KaroModel.objects.all()
    kcolsum=object_list.aggregate(Sum("kcol"))
    golekcolmax=object_list.aggregate(Max("goleKcol"))

    #####################目標カロリーの表示##############################
    last_order = KaroModel.objects.order_by("id").last()
    golekcolcount=object_list.aggregate(Count("goleKcol"))
    golekcolcount=golekcolcount["goleKcol__count"]

    l=[]
    for i in object_list:
        l.append(i.id)
    
    gole=0
    if KaroModel!=None and len(l)>1:
        gole=last_order.goleKcol
        print(gole)
        print(golekcolmax["goleKcol__max"])
        print(KaroModel.objects.get(pk=l[-2]).goleKcol)
        if (gole == 0) or (gole < golekcolmax["goleKcol__max"]):
            if (KaroModel.objects.get(pk=l[-2]).goleKcol == 0):        
                for i in object_list:
                    if 0 != i.goleKcol:
                        gole = i.goleKcol
                        print(gole)
                print(gole)  
            elif (gole != KaroModel.objects.get(pk=l[-2]).goleKcol):
                
                if gole==0:
                    for i in object_list:
                        if 0 != i.goleKcol:
                            gole = i.goleKcol
                gole = gole

            else:
                gole=KaroModel.objects.get(pk=l[-2]).goleKcol
        else:
            gole=last_order.goleKcol
        
    else:
        gole=0
        for i in object_list:
            gole = i.goleKcol 
    ###################### ここまで　############################

    #摂取カロリーの合計
    if kcolsum["kcol__sum"] == None:
        kcolsum["kcol__sum"]=0
        lastkcal = gole-kcolsum["kcol__sum"]
    else:
        lastkcal = gole-kcolsum["kcol__sum"]


    dt_now = datetime.datetime.now()

    return render(request, "list.html", {"object_list": object_list, "kcolsum":kcolsum, "golekcolmax":golekcolmax,
    "last_order":last_order, "gole":gole, "dt_now":dt_now,"lastkcal":lastkcal, "golekcolcount":golekcolcount})

    


#詳細
class KaroDetail(DetailView):
    template_name="detail.html"
    model = KaroModel

#作成
class KaroCreate(CreateView):
    template_name="create.html"
    model = KaroModel
    
    fields = ("eat", "kcol", "daycolor", "date", "goleKcol", )
    success_url = reverse_lazy("list")

#削除
class KaroDelete(DeleteView):
    template_name="delete.html"
    model = KaroModel
    success_url = reverse_lazy("list")

#更新
class KaroUpdate(UpdateView):
    template_name="update.html"
    model = KaroModel
    fields = ("eat", "kcol", "daycolor")
    success_url = reverse_lazy("list")

#全削除
def fulldelete(request):
    template_name = "fulldelete.html"
    if request.POST:
        KaroModel.objects.all().delete()
        return redirect("list")
    return render(request, template_name)
    


    

    

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>カロリー管理</title>
<!-- 追加 -->
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<script
  src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.2.0/chart.min.js"
  integrity="sha512-VMsZqo0ar06BMtg0tPsdgRADvl0kDHpTbugCBBrL55KmucH6hP9zWdLIWY//OTfMnzz6xWQRxQqsUFefwHuHyg=="
  crossorigin="anonymous"></script>
<script
  src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns@next/dist/chartjs-adapter-date-fns.bundle.min.js"></script>

  
    
  </head>
  <body class="bg-dark">
    <div class="width:100%; container my-3">
    {% block header %}
    {% endblock %}
    </div>

    <div class="container p-0  mb-3">
      <div class="row">
        <div class="col-lg-4 mb-5">
          {% block sidebar %}
          {% endblock %}
        </div>
        <div class="col-lg-8 mb-5">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
    

    <div class="fixed-bottom mx-0 text-white text-center bg-secondary">
    {% block footer %}
    {% endblock %}
     </div>
  </body>
</html>

templates/create.html
{% extends "base.html" %}

{% block header %}
<div class="text-white sticky-top w-100 p-1  mb-3 bg-dark">
  <figure class="text-center">
    <blockquote class="blockquote mb-3">
      <p>
        Muscle-Health-blog</p>
    </blockquote>
    <figcaption class="blockquote-footer mb-3">
        Create New
    </figcaption>
  </figure>
  </div>
{% endblock %}

{% block sidebar %}

<form action="" method="POST" class="container text-center text-white bg-dark">{% csrf_token %}
    <div class="m-2 p-2 text-center bg-secondary">
        <label for="name">Enter new eat </label><br>
        >> {{ form.eat }}
      </div>
    <div class="m-2 p-2 text-center ">
        <label for="name">Enter new kcal </label><br>
        >> {{ form.kcol }}
      </div>
    <div class="m-2 p-2 text-center bg-secondary">
        <label for="name">Select new daycolor </label><br>
        >> {{ form.daycolor }}
      </div>
    <div class="m-2 p-2 text-center ">
        <label for="name">Enter new date </label><br>
        >> {{ form.date }}
      </div>
    <div class="m-2 p-2 text-center bg-secondary">
        <label for="name">Enter new target calorie <br>
            <p class="text-dark">*If you do not change your target calorie, you do not need to change it from 0.</p>
            <p class="text-dark">*If you want to change the target calorie, please enter the target calorie and change it.</p>
        </label><br>
        >> {{ form.goleKcol }}
      </div>

    <!--{{from}} はモデルで指定しているデータをfromの形で表示できる-->
    <input type="submit" value="CREATE" class="btn  btn-outline-success btn-lg text-success m-2 p-2">
</form>
{% endblock%}

{% block content %} 
{% endblock %}


{% block footer %}
	<div class="row ">
		<div class="col-12">
            <p class="p-1">	ロニー・コールマン ~
                True training starts when you want to quit~</p>
        </div>
	</div>
{% endblock %}

templates/delete.html
{% extends 'base.html' %}

{% block header %}
<div class="text-white sticky-top w-100 p-1  mb-3 bg-dark">
  <figure class="text-center">
    <blockquote class="blockquote mb-3">
      <p>
        Muscle-Health-blog</p>
    </blockquote>
    <figcaption class="blockquote-footer mb-3">
        Deleted information
    </figcaption>
  </figure>
  </div>
{% endblock %}


{% block sidebar %}
<div class="container bg-dark">
    <ul class="list-group list-group-flush ">
      <li class="list-group-item bg-secondary text-white text-center">Eat : {{object.eat}}</li>
      <li class="list-group-item bg-dark text-white text-center">Kcal : {{object.kcol}}</li>
      <li class="list-group-item bg-secondary text-white text-center">When : {{object.get_daycolor_display}}</li>
      <li class="list-group-item bg-dark text-white text-center">Registration time : {{object.date}}</li>
    </ul>
</div>

<div class="container bg-dark mt-3">
<form action="" method="POST" class="container text-center">{% csrf_token %}
    <input type="submit" value="DELETE" class="btn  btn-outline-danger btn-lg text-danger">
</form>
</div>

{% endblock%}


{% block content %}
{% load static%}  

{% endblock %}


{% block footer %}
	<div class="row ">
		<div class="col-12">
            <p class="p-1">	ヘンリー・ロリンズ ~
                I consider iron my best friend. Never piss me off, never run away. Friends may come, but someday they will leave. But £200 is always £200~</p>
        </div>
	</div>
{% endblock %}

templates/detail.html
{% extends 'base.html' %}

{% load mathfilters %}

{% block header %}
<div class="text-white sticky-top w-100 p-1  mb-3 bg-dark">
  <figure class="text-center">
    <blockquote class="blockquote mb-3">
      <p>
        Muscle-Health-blog</p>
    </blockquote>
    <figcaption class="blockquote-footer mb-3">
      Detailed information
    </figcaption>
  </figure>
  </div>
{% endblock %}


{% block sidebar %}
<div class="container bg-dark">
<ul class="list-group list-group-flush ">
  <li class="list-group-item bg-secondary text-white text-center">Eat : {{object.eat}}</li>
  <li class="list-group-item bg-dark text-white text-center">Kcal : {{object.kcol}}</li>
  <li class="list-group-item bg-secondary text-white text-center">When : {{object.get_daycolor_display}}</li>
  <li class="list-group-item bg-dark text-white text-center">Registration time : {{object.date}}</li>
</ul>
</div>
{% endblock %}


{% block content %}
{% endblock %}


{% block footer %}
<div class=" fixed-bottom text-white text-center  bg-secondary">
	<div class="row ">
		<div class="col-12">
      <p class="p-1">	ドリアン・イエーツ ~
        What would you do if a stranger just walked in the door, put a gun to your temple and said, "Do it two more times"? You're going crazy for death, aren't you? That's what it means to push.~</p>
      
    </div>
	</div>
</div>
{% endblock %}

templates/fulldelete.html
{% extends "base.html" %}

{% block header %}
<div class="text-white sticky-top w-100 p-1  mb-3 bg-dark">
  <figure class="text-center">
    <blockquote class="blockquote mb-3">
      <p>
        Muscle-Health-blog</p>
    </blockquote>
    <figcaption class="blockquote-footer mb-3">
        Delete all data
    </figcaption>
  </figure>
  </div>
{% endblock %}


{% block sidebar %}
<form action="" method="POST" class="text-white container text-center">{% csrf_token %}
    <p>Delete all data.</p>
    <p>*Deleted data will not be recovered</p>

    <input type="submit" value="ALL_DELETE" class="btn  btn-outline-danger btn-lg text-danger m-2 p-2">
</form>
{% endblock %}

{% block content %}
{% endblock %}

{% block footer %}
<div class=" fixed-bottom text-white text-center  bg-secondary">
	<div class="row ">
		<div class="col-12">
            <p class="p-1">	ドウェイン・ジョンソン ~
                Show with actions rather than words~</p>
    </div>
	</div>
</div>
{% endblock %}

templates/list.html
{% extends 'base.html' %}

{% block header %}
<div class="text-white sticky-top w-100 p-2 my-3">
  <figure class="text-center">
    <blockquote class="blockquote mb-3">
      <p>
        Muscle-Health-blog</p>
    </blockquote>
    <figcaption class="blockquote-footer mb-3">
      Muscle and health  <cite title="Source Title">don't betray</cite>
    </figcaption>
    <figcaption class="blockquote-footer ">
      {{dt_now}}
    </figcaption>
  </figure>
  </div>
{% endblock %}

<!--リスト表示、操作-->
{% block sidebar %}
<div class="container p-2 text-white">
  <!--データの数を表示、CREATEした数-->
  <p class="container text-end fst-normal fs-3">The number of data : {{golekcolcount}}</p>
  <!--create:新規作成、 fulldelete:全削除　のボタン押すと、指定されたページに移動-->
  <div class="container m-2">
    <a href="{% url 'create'%}" class="btn btn-outline-success mb-2" tabindex="-1" role="button" aria-disabled="true">NEW_CREATE</a>
    <a href="{% url 'fulldelete' %}" class="btn btn-outline-danger mb-2" tabindex="-1" role="button" aria-disabled="true">FULLDELETE</a>
  </div>

  <div class="overflow-auto p-3" style="width:auto; height:400px;">
  {% for item in object_list %}
  <!--リスト表示（update:更新、 delete:削除　detail:詳細）-->
  <div class='alert alert-{{item.daycolor}} ' role="alert">
    <p>{{item.eat}}　期日：{{item.date | date:"o/n/j P"}}</p>
    <a href="{% url 'update' item.pk %}" class="btn btn-dark " tabindex="-1" role="button" aria-disabled="true">UPDATE</a>
    <a href="{% url 'delete' item.pk %}" class="btn btn-secondary " tabindex="-1" role="button" aria-disabled="true">DELETE</a>
    <a href="{% url 'detail' item.pk %}" class="btn btn-light " tabindex="-1" role="button" aria-disabled="true">DETAIL</a>
  </div>
{% endfor %}
  </div>
</div>
{% endblock %}


<!--グラフ-->
{% block content %}
<div class="p-3 mt-10 text-white">
<!--目標カロリー-->
<p class="fst-normal fs-3">Target calorie：{{gole}}kcal</p>
<!--摂取カロリーの合計-->
<p class="fst-normal fs-3">Today's calorie intake：{{kcolsum.kcol__sum}}kcal</p>
<!--目標カロリーと摂取カロリーの差-->
<p class="fst-normal fs-3">Remaining target calorie：<br>
  >>><span class="text-danger">{{lastkcal}}</span> kcal</p>

<!--グラフの表示（棒グラフ、現在の摂取カロリーと目標カロリー）-->
<div class="w-100 p-3 ">
  <canvas id="mychart-bar" width="400" height="200"></canvas>
</div>

<script>
Chart.defaults.animation.duration = 1000;
var ctx = document.getElementById('mychart-bar');
var myChart = new Chart(ctx, {
  type: 'bar',
  data: {
    labels: ['KCAL'],
    datasets: [{
      label: 'NowKcar',
      data: ["{{kcolsum.kcol__sum}}"],
      backgroundColor: '#ced4da',
    },{
      label: 'GoalKcal',
      data: ["{{gole}}"],
      backgroundColor: '#6c757d',
    }],
  },
});
</script>
</div>
</div>
{% endblock %}


{% block footer %}
<div class=" fixed-bottom text-white text-center  bg-secondary">
	<div class="row ">
		<div class="col-12">
      <p class="p-1">	アーノルド・シュワルツェネッガー ~If your muscles say NO, I say YES! and answer.~</p>
    </div>
	</div>
</div>
{% endblock %}

templates/update.html
{% extends 'base.html' %}

{% load mathfilters %}

{% block header %}
<div class="text-white sticky-top w-100 p-1  mb-3 bg-dark">
  <figure class="text-center">
    <blockquote class="blockquote mb-3">
      <p>
        Muscle-Health-blog</p>
    </blockquote>
    <figcaption class="blockquote-footer mb-3">
        Data update
    </figcaption>
  </figure>
  </div>
{% endblock %}

{% block sidebar %}

<form action="" method="POST" class="container text-center text-white">{% csrf_token %}
    <div class="m-2 p-2 text-center bg-secondary">
        <label for="name">Enter update eat </label><br>
        >> {{ form.eat }}
      </div>
    <div class="m-2 p-2 text-center ">
        <label for="name">Enter update kcal </label><br>
        >> {{ form.kcol }}
      </div>
    <div class="m-2 p-2 text-center bg-secondary">
        <label for="name">Select update daycolor </label><br>
        >> {{ form.daycolor }}
      </div>

    <!--{{from}} はモデルで指定しているデータをfromの形で表示できる-->
    <input type="submit" value="UPDATE" class="btn  btn-outline-success btn-lg text-success m-2 p-2">
</form>
{% endblock%}

{% block content %} 
{% endblock %}


{% block footer %}
	<div class="row ">
		<div class="col-12">
            <p class="p-1">	ジェレミー・ブエンディア ~
                No kidding, training right now!~</p>
        </div>
	</div>
{% endblock %}